#!/usr/bin/env python3
"""Walk bundles/ and report which PDFs already contain an AcroForm.

`fitz.Document.is_form_pdf` is true iff the PDF catalog has a /AcroForm
dict whose /Fields array is non-empty — that matches the upload
pipeline's notion of "already fillable, no detection needed". Widgets
per page are counted as a sanity check (a form with /Fields but no
visible widgets is unusual and worth flagging separately).
"""
from __future__ import annotations

import json
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import fitz


ROOT = Path('/Users/raduiamandi/Projects/tipizatul.eu/scripts/edirect/bundles')
OUT = Path(__file__).resolve().parent / 'acroform-scan.json'


# pdf-lib (https://github.com/Hopding/pdf-lib) is the writer used by the
# tipizatul AcroForm pipeline. A bundles/ PDF with pdf-lib as /Producer
# was generated by us, not by the source institution — treat as
# "pipeline-generated", not "original AcroForm".
PIPELINE_PRODUCERS = ('pdf-lib',)


def inspect(path_str: str) -> dict:
    p = Path(path_str)
    try:
        with fitz.open(path_str) as d:
            is_form = bool(d.is_form_pdf)
            n_widgets = 0
            producer = ''
            creator = ''
            if is_form:
                for page in d:
                    n_widgets += sum(1 for _ in page.widgets())
                m = d.metadata or {}
                producer = m.get('producer') or ''
                creator = m.get('creator') or ''
            origin = 'plain'
            if is_form:
                origin = ('pipeline'
                          if any(s in producer for s in PIPELINE_PRODUCERS)
                          else 'original')
            return {'path': path_str, 'size': p.stat().st_size,
                    'pages': d.page_count, 'is_form': is_form,
                    'widgets': n_widgets, 'producer': producer,
                    'creator': creator, 'origin': origin}
    except Exception as exc:
        return {'path': path_str, 'error': str(exc)[:200]}


def main() -> int:
    paths = [str(p) for p in ROOT.rglob('*.pdf')
             if '/processed/' not in str(p) and p.is_file()]
    print(f'Scanning {len(paths)} PDFs…', flush=True)

    results: list[dict] = []
    with ProcessPoolExecutor(max_workers=6) as ex:
        futures = [ex.submit(inspect, p) for p in paths]
        for i, fut in enumerate(as_completed(futures), 1):
            results.append(fut.result())
            if i % 500 == 0:
                print(f'  {i}/{len(paths)}', flush=True)

    forms    = [r for r in results if r.get('is_form')]
    original = [r for r in forms   if r.get('origin') == 'original']
    pipeline = [r for r in forms   if r.get('origin') == 'pipeline']
    plain    = [r for r in results if r.get('is_form') is False]
    errored  = [r for r in results if 'error' in r]

    out = {
        'total': len(results),
        'acroform_total': len(forms),
        'acroform_original': len(original),
        'acroform_pipeline': len(pipeline),
        'plain': len(plain),
        'errored': len(errored),
        'original_paths': sorted(r['path'] for r in original),
        'pipeline_paths': sorted(r['path'] for r in pipeline),
        'errors': errored,
    }
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2),
                   encoding='utf-8')

    print()
    print(f'Total scanned:               {len(results):>5}')
    print(f'AcroForm present:            {len(forms):>5}'
          f'  ({len(forms)/len(results):.1%})')
    print(f'  original (from institution): {len(original):>5}')
    print(f'  pipeline-generated (pdf-lib):{len(pipeline):>5}')
    print(f'Plain PDFs:                  {len(plain):>5}')
    print(f'Errors:                      {len(errored):>5}')
    print()
    top_orig = sorted(original, key=lambda x: -x['widgets'])[:8]
    if top_orig:
        print('Top 8 ORIGINAL AcroForm PDFs by widget count:')
        for r in top_orig:
            print(f"  {r['widgets']:>4} widgets, {r['pages']}p — "
                  f"{Path(r['path']).name[:70]}")
        print()
    print(f'Saved to {OUT}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
